config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :posts
  resources :comments
end

app/models/PostsAndComments.rb
class PostsAndComments
  attr_accessor :title, :content, :created_at, :record_type

  def initialize(hash)
    @title       = hash['title']
    @content     = hash['content']
    @created_at  = hash['created_at']
    @record_type = hash['record_type']
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save ? (redirect_to comment_url(@comment)) : (render :new)
  end

  def update
    @comment.update(comment_params) ? (redirect_to comment_url(@comment)) : (render :edit)
  end

  def destroy
    @comment.destroy
    redirect_to comments_url
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @records = Post.find_by_sql("
      SELECT title, content, created_at, 'Post' as record_type
      FROM posts
      UNION
      SELECT NULL as title, comments.content, comments.created_at, 'Comment' as record_type
      FROM comments
      INNER JOIN posts ON posts.id = comments.post_id
      ORDER BY created_at ASC, content ASC;
    ")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save ? (redirect_to post_url(@post)) : (render :new)
  end

  def update
    @post.update(post_params) ? (redirect_to post_url(@post)) : (render :edit)
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="shadow rounded p-5">
  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>
</div>

app/views/comments/_form.html.erb
<div class="shadow rounded p-5">
  <%= simple_form_for(@comment) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :post_id %>
      <%= f.input :content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1 class="mb-5">Editing comment</h1>

<%= render "form", comment: @comment %>

<br>
<div class="btn-group my-5">
  <%= link_to "Show this comment", @comment, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to comments", comments_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/comments/index.html.erb
<h1 class="mb-5">Comments</h1>

<% @comments.each do |comment| %>
  <%= render comment %>
  <p><%= link_to "Show this comment", comment, class: "btn btn-sm btn-outline-dark mt-3" %></p>
<% end %>

<%= link_to "New comment", new_comment_path, class: "btn btn-sm btn-outline-dark" %>

app/views/comments/new.html.erb
<h1 class="mb-5">New comment</h1>

<%= render "form", comment: @comment %>

<br>
<div>
  <%= link_to "Back to comments", comments_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/comments/show.html.erb
<%= render @comment %>

<div class="btn-group my-5">
  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to comments", comments_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this comment", @comment, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Find By SQL</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_post_path %>">Create Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= comments_path %>">Comments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_comment_path %>">Create Comment</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Find By SQL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5 pb-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="display-1 text-success mb-5">
  General Data
</h1>

<table class="table  table-bordered shadow">
  <thead>
    <tr>
      <th>Record Type</th>
      <th>Content</th>
      <th>Created At</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.record_type %></td>
        <td><%= record.content %></td>
        <td><%= record.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_form.html.erb
<div class="shadow rounded p-5">
  <%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="shadow rounded p-5">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1 class="mb-5">Editing post</h1>

<%= render "form", post: @post %>

<br>
<div class="btn-group my-5">
  <%= link_to "Show this post", @post, class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/posts/index.html.erb
<h1 class="mb-5">Posts</h1>

<% @posts.each do |post| %>
  <%= render post %>
  <p><%= link_to "Show this post", post, class: "btn btn-sm btn-outline-dark mt-3" %></p>
<% end %>

<%= link_to "New post", new_post_path, class: "btn btn-sm btn-outline-dark" %>

app/views/posts/new.html.erb
<h1 class="mb-5">New post</h1>

<%= render "form", post: @post %>

<br>
<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div class="btn-group my-5">
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-sm btn-outline-dark" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-sm btn-outline-dark" %>
  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-sm btn-outline-dark" %>
</div>